spring:

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "co.istad.chan.paymentservice.events"
        spring.json.value.default.type: co.istad.chan.paymentservice.events.SeatReservedEvent
        spring.json.use.type.headers: false
      auto-offset-reset: latest



  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:7168/
    username: itpusr
    password: itp@168
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9998


